# Generated by Django 4.1.5 on 2023-01-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tags_scope'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scope',
            new_name='Scopes',
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематики статьи'},
        ),
        migrations.RenameField(
            model_name='scopes',
            old_name='tags',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=16, verbose_name='Тэг'),
        ),
    ]
